version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@4.0.1

workflows:
  build_and_push_image:
    jobs:
      - aws-ecr/build_and_push_image:
          create-repo: true
          repo: $AWS_ECR_ACCOUNT_URL/event-driven-architecture
